"""Auto-generate FAQ JSON files from an indexed KVForge corpus.

Uses the loaded LLM to produce one factual Q&A pair per sampled chunk.
Generated FAQs can be used directly for LoRA instruction fine-tuning
(``lora_trainer.py --faqs``) and PRS evaluation (``prs_evaluator.py``).

Algorithm:

1. Sample up to ``count * 2`` chunk texts from the vector store collection.
2. For each chunk, fill ``QA_PROMPT_TEMPLATE`` and call the LLM pipeline.
3. Parse the ``Q:`` / ``A:`` lines from the output with ``_parse_qa``.
4. Stop once ``count`` valid Q&A pairs have been collected.
5. Write the result to *output* as a JSON array.

Usage::

    python tools/generate_faqs.py --config datasource_example.json \\
        --count 50 --output faqs.json
"""

import argparse
import json
import random
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


QA_PROMPT_TEMPLATE = """Read the following passage and generate exactly one factual question and answer pair about it.

Passage:
{chunk}

Respond in this exact format:
Q: <question>
A: <answer>"""


def _parse_qa(text: str):
    """Parse a single Q&A pair from raw LLM output text.

    Looks for lines matching ``Q:`` / ``Question:`` and ``A:`` / ``Answer:``
    (case-insensitive).

    Args:
        text: Raw text generated by the LLM after the prompt.

    Returns:
        A ``(question, answer)`` string tuple, or ``None`` if the expected
        markers are not found or either value is empty after stripping.
    """
    q_match = re.search(r"(?:Q|Question):\s*(.+?)(?:\n|$)", text, re.IGNORECASE)
    a_match = re.search(r"(?:A|Answer):\s*(.+?)(?:\n|$)", text, re.IGNORECASE | re.DOTALL)
    if not q_match or not a_match:
        return None
    q = q_match.group(1).strip()
    a = a_match.group(1).strip()
    if not q or not a:
        return None
    return q, a


def _sample_chunks(store, collection: str, n: int) -> list[str]:
    """Sample up to *n* chunk text strings from the vector store collection.

    Retrieves up to 500 chunks via a single scroll call and then randomly
    samples *n* of them.

    Args:
        store: VectorStore instance (or a raw ``QdrantClient``).
        collection: Collection name to scroll.
        n: Maximum number of chunk texts to return.

    Returns:
        List of up to *n* chunk text strings chosen uniformly at random.
    """
    results, _ = store.scroll(collection, limit=500, with_payload=True, with_vectors=False)
    texts = [r.payload.get("text", "") for r in results if r.payload.get("text")]
    return random.sample(texts, min(n, len(texts)))


def generate(cfg: dict, count: int, output_path: str) -> None:
    """Run the full FAQ generation loop and save results to *output_path*.

    Loads the LLM once, samples ``count * 2`` chunks (to allow for parse
    failures), prompts the model for each, parses the output, and writes
    exactly *count* (or fewer, if not enough parses succeed) Q&A dicts to
    *output_path*.

    Args:
        cfg: Datasource configuration dict.  Uses ``llm_model``,
            ``faq_question_key``, ``faq_answer_key``, ``qdrant_host``,
            ``qdrant_port``, and ``collection``.
        count: Target number of FAQs to generate.
        output_path: Destination file path for the JSON output.
    """
    import core.model_loader as model_loader

    model_loader.init(cfg)
    model, tokenizer = model_loader.load()

    from transformers import pipeline as hf_pipeline
    pipe = hf_pipeline("text-generation", model=model, tokenizer=tokenizer,
                        max_new_tokens=128, do_sample=False)

    # Use VectorStore abstraction if available, else fall back to direct qdrant
    try:
        from vectorstore.registry import get_store
        store = get_store(cfg)
    except ImportError:
        from qdrant_client import QdrantClient
        store = QdrantClient(host=cfg["qdrant_host"], port=cfg["qdrant_port"])

    sampled = _sample_chunks(store, cfg["collection"], n=count * 2)

    q_key = cfg.get("faq_question_key", "question")
    a_key = cfg.get("faq_answer_key", "answer")
    faqs = []

    for chunk in sampled:
        if len(faqs) >= count:
            break
        prompt = QA_PROMPT_TEMPLATE.format(chunk=chunk[:1000])
        out = pipe(prompt)[0]["generated_text"][len(prompt):].strip()
        parsed = _parse_qa(out)
        if parsed is None:
            continue
        q, a = parsed
        faqs.append({q_key: q, a_key: a})
        print(f"  [{len(faqs)}/{count}] Q: {q[:80]}")

    with open(output_path, "w") as f:
        json.dump(faqs, f, indent=2, ensure_ascii=False)
    print(f"\nSaved {len(faqs)} FAQs to {output_path}")


def main() -> None:
    p = argparse.ArgumentParser(description="Auto-generate FAQs from an indexed corpus")
    p.add_argument("--config", required=True, help="Datasource config JSON")
    p.add_argument("--count", type=int, default=50, help="Number of FAQs to generate")
    p.add_argument("--output", default="generated_faqs.json", help="Output JSON path")
    args = p.parse_args()

    with open(args.config) as f:
        cfg = json.load(f)
    generate(cfg, args.count, args.output)


if __name__ == "__main__":
    main()
