"""Download and prepare LongBench datasets for KVForge ingestion.

LongBench's dataset loading script is deprecated by the `datasets` library, so
this script downloads the raw `data.zip` from HuggingFace and extracts the
JSONL files directly.

For each requested task, it produces:

* ``examples/longbench_<task>/data/<task>.chunks.json`` — passages as chunks
* ``examples/longbench_<task>/eval_<task>.json`` — questions + answers
* ``examples/longbench_<task>/config.json`` — KVForge datasource config

The script does **not** run KV indexing; that is done separately with the
existing KVForge pipeline on the GPU host.

Usage::

    python3 -m tools.ingest_longbench --tasks 2wikimqa hotpotqa musique

"""

from __future__ import annotations

import argparse
import json
import os
import re
import zipfile
from pathlib import Path

from huggingface_hub import hf_hub_download


LONGBENCH_REPO = "THUDM/LongBench"
LONGBENCH_ZIP = "data.zip"


def download_longbench(cache_dir: Path) -> Path:
    """Download LongBench data.zip and return the local path."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    zip_path = hf_hub_download(
        repo_id=LONGBENCH_REPO,
        filename=LONGBENCH_ZIP,
        repo_type="dataset",
        local_dir=str(cache_dir),
        local_dir_use_symlinks=False,
    )
    return Path(zip_path)


def extract_jsonl(zip_path: Path, task: str, extract_dir: Path) -> Path:
    """Extract a single JSONL file from the zip to extract_dir."""
    with zipfile.ZipFile(zip_path, "r") as z:
        member = f"data/{task}.jsonl"
        z.extract(member, extract_dir)
    return extract_dir / member


def split_passages(context: str) -> list[str]:
    """Split a LongBench context into individual passages.

    LongBench concatenates passages with ``Passage N:\n`` headers.
    """
    # Use regex to split on "Passage N:" headers, preserving the text after each.
    parts = re.split(r"\nPassage \d+:\n", context)
    # The first part may be empty or contain "Passage 1:" prefix.
    passages = []
    for p in parts:
        p = p.strip()
        if p.startswith("Passage 1:"):
            p = p[len("Passage 1:") :].strip()
        if p:
            passages.append(p)
    return passages


def build_kvforge_dataset(
    task: str,
    jsonl_path: Path,
    output_dir: Path,
    llm_model: str = "meta-llama/Llama-3.2-3B-Instruct",
) -> None:
    """Build KVForge datasource files for a LongBench task."""
    output_dir.mkdir(parents=True, exist_ok=True)
    data_dir = output_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    all_chunks: list[str] = []
    eval_items: list[dict] = []
    seen_ids: set[str] = set()

    with open(jsonl_path) as f:
        for line in f:
            row = json.loads(line)
            qid = row.get("_id", f"{len(eval_items)}-{hash(line) & 0xffffffff}")
            if qid in seen_ids:
                continue
            seen_ids.add(qid)

            passages = split_passages(row.get("context", ""))
            all_chunks.extend(passages)

            # LongBench answers are a list; use the first as primary ground truth.
            answers = row.get("answers", [])
            ground_truth = answers[0] if answers else ""
            eval_items.append({
                "question": row.get("input", ""),
                "answer": ground_truth,
                "all_answers": answers,
                "id": qid,
                "dataset": row.get("dataset", task),
                "length": row.get("length"),
            })

    # Save chunks
    chunks_path = data_dir / f"{task}.chunks.json"
    with open(chunks_path, "w") as f:
        json.dump({"chunks": all_chunks}, f, indent=2)

    # Save eval set
    eval_path = output_dir / f"eval_{task}.json"
    with open(eval_path, "w") as f:
        json.dump({
            "version": "v1",
            "task": task,
            "source": LONGBENCH_REPO,
            "n_items": len(eval_items),
            "items": eval_items,
        }, f, indent=2)

    # Save config
    config = {
        "_comment": f"LongBench {task} — generated by tools.ingest_longbench",
        "use_case_name": f"LongBench {task}",
        "collection": f"longbench-{task}",
        "version_file": f"examples/longbench_{task}/version.json",
        "addons": ["indexing", "inference", "training", "background", "sync", "monitoring"],
        "addon_config": {
            "indexing": {
                "loader": "jsonl",
                "chunk_size": 600,
                "chunk_overlap": 60,
                "embed_batch": 64,
                "upsert_batch": 128,
                "embed_model": "BAAI/bge-small-en-v1.5",
                "embedder_backend": "fastembed",
                "vector_dim": 384,
                "vector_store": "qdrant",
                "qdrant_host": "localhost",
                "qdrant_port": 6333,
                "model_library": {
                    llm_model: {
                        "kv_num_layers": 28,
                        "kv_num_heads": 8,
                        "kv_head_dim": 128,
                    }
                },
            },
            "inference": {
                "top_k": 5,
                "llm_model": llm_model,
                "quantization": "4bit",
                "max_new_tokens": 256,
                "gate_threshold": 0.75,
                "recompute_ratio": 0.0,
            },
            "training": {
                "lora_rank": 16,
                "lora_alpha": 32,
                "lora_target_modules": ["q_proj", "k_proj", "v_proj"],
                "lora_dropout": 0.05,
                "lora_epochs": 3,
                "lora_lr": 0.0002,
                "checkpoint_dir": f"examples/longbench_{task}/lora_checkpoints/",
                "replay_db": f"examples/longbench_{task}/replay.db",
                "prs_weights": {"accuracy": 0.7, "calibration": 0.15, "consistency": 0.15},
                "prs_advancement_threshold": 0.72,
                "prs_regression_threshold": 0.25,
                "phase2_advance_threshold": 0.30,
                "phase3_advance_threshold": 0.55,
                "faq_question_key": "question",
                "faq_answer_key": "answer",
            },
            "background": {"flush_seconds": 300, "flush_queries": 50},
            "sync": {
                "interval_minutes": 1440,
                "hitl_mode": "auto",
                "sync_regression_mode": "pct",
                "sync_regression_pct_threshold": 0.10,
                "sync_regression_tier_threshold": 0.15,
            },
            "monitoring": {"port": 8085},
        },
    }
    config_path = output_dir / "config.json"
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

    print(f"   {task}: {len(all_chunks)} chunks, {len(eval_items)} eval items")
    print(f"      chunks: {chunks_path}")
    print(f"      eval:   {eval_path}")
    print(f"      config: {config_path}")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--tasks", nargs="+", default=["2wikimqa", "hotpotqa", "musique"],
                   help="LongBench tasks to ingest")
    p.add_argument("--cache-dir", default="/tmp/longbench",
                   help="Where to cache the downloaded LongBench zip")
    p.add_argument("--output-root", default="examples",
                   help="Root directory for generated KVForge examples")
    p.add_argument("--llm-model", default="meta-llama/Llama-3.2-3B-Instruct")
    args = p.parse_args()

    cache_dir = Path(args.cache_dir)
    print("📥 Downloading LongBench data.zip...")
    zip_path = download_longbench(cache_dir)
    print(f"   → {zip_path}")

    extract_dir = cache_dir / "extracted"
    print("📝 Preparing KVForge datasets...")
    for task in args.tasks:
        jsonl_path = extract_jsonl(zip_path, task, extract_dir)
        output_dir = Path(args.output_root) / f"longbench_{task}"
        build_kvforge_dataset(task, jsonl_path, output_dir, llm_model=args.llm_model)

    print("\n💡 Next: run KVForge indexing on each dataset to compute chunks + KV tensors.")


if __name__ == "__main__":
    main()

