"""Synthetic factual noise injection for absorption-curve quality experiments.

Replaces a configurable fraction of corpus chunks with plausible-but-factually-
wrong rewrites generated by a cloud LLM. Used to measure how noise affects
Path B (parametric) vs Path A (text RAG) accuracy.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np


def _call_llm(prompt: str, provider: str, model: str, api_key: str) -> str:
    """Call a cloud LLM via the existing sleep_faq_generator._call_provider."""
    from pipeline.sleep_faq_generator import _call_provider
    return _call_provider(provider, model, api_key, prompt)


def _build_noise_prompt(original_text: str) -> str:
    """Build a prompt that asks the LLM to rewrite the text with subtle factual errors."""
    return (
        "Rewrite the following text so that it sounds plausible and well-written, "
        "but contains 2-3 subtle factual errors (wrong numbers, swapped names, "
        "incorrect relationships). Keep the same structure and tone.\n\n"
        f"Original text:\n{original_text}\n\n"
        "Output only the rewritten text, no preamble."
    )


def _select_noise_targets(chunks: list[dict], noise_rate: float, seed: int = 42) -> list[int]:
    """Deterministically select which chunk indices to corrupt."""
    n = len(chunks)
    n_corrupt = int(n * noise_rate)
    if n_corrupt == 0:
        return []
    rng = np.random.RandomState(seed)
    return rng.choice(n, size=n_corrupt, replace=False).tolist()


def inject_noise(
    chunks: list[dict],
    noise_rate: float,
    provider: str = "gemini",
    model: str = "gemini-2.5-flash",
    api_key: str = "",
) -> list[dict]:
    """Return a copy of *chunks* with *noise_rate* fraction factually corrupted.

    Args:
        chunks: List of chunk dicts with ``text`` and ``chunk_id``.
        noise_rate: Fraction of chunks to corrupt (0.0 = none, 1.0 = all).
        provider: Cloud LLM provider (``gemini``, ``claude``, ``openai``).
        model: Cloud LLM model name.
        api_key: API key for the provider.

    Returns:
        New list of chunk dicts; corrupted chunks have modified ``text``
        and an added ``is_noisy: True`` field.
    """
    import copy
    result = [copy.deepcopy(c) for c in chunks]
    targets = _select_noise_targets(chunks, noise_rate)

    for idx in targets:
        original = result[idx].get("text", "")
        if not original:
            continue
        prompt = _build_noise_prompt(original)
        noisy_text = _call_llm(prompt, provider, model, api_key)
        result[idx]["text"] = noisy_text.strip()
        result[idx]["is_noisy"] = True

    return result
